### ISSUE TITLE
How to build for MKS_Eagle with marlin

### ISSUE THREAD

**Issue by Voxel3DPrinting** [makerbase-mks/MKS-EAGLE#3]
Dear,

I want to build a 3D printer with this motherboard. however, when I try to compile Marlin 2.0.9.2, the Platform.ini environment is not compatible.. (I mean the phrase next to "include_envs = ....."  What should I put here to compile my own firmware?
Hope to hear from support.
Thanks in advance

```
[platformio]
src_dir      = Marlin
boards_dir   = buildroot/share/PlatformIO/boards
**default_envs = Atmega2560**
include_dir  = Marlin
extra_configs =
    ini/avr.ini
    ini/due.ini
    ini/esp32.ini
    ini/features.ini
    ini/lpc176x.ini
    ini/native.ini
    ini/samd51.ini
    ini/stm32-common.ini
    ini/stm32f0.ini
    ini/stm32f1-maple.ini
    ini/stm32f1.ini
    ini/stm32f4.ini
    ini/stm32f7.ini
    ini/stm32h7.ini
    ini/teensy.ini
```

**Comment by mks-viva** [comment]
1. In platform.ini file, set env = mks_eagle #or 'mks_eagle_usb_flash_drive',  mks_eagle_usb_flash_drive_msc
2. In Configuration.h file, set BOARD as BOARD_MKS_EAGLE; enable 'MKS_TS35_V2'; enable LVGL UI or other UI

**Comment by Voxel3DPrinting** [comment]
thanks!
