### ISSUE TITLE
Microstepping

### ISSUE THREAD

**Issue by Voxel3DPrinting** [makerbase-mks/MKS-EAGLE#5]
Hi, is this motherboard capable of 1/256 microstepping?

**Comment by MKS-hosiey** [comment]
Support, what driver do you use?

**Comment by Voxel3DPrinting** [comment]
mks eagle, so onboard TMC2209 uart

**Comment by MKS-hosiey** [comment]
Hello, you can set this subdivision in the advanced settings, but this TMC2209 driver does not need to be set to 256 subdivisions, it is internally expanded to 256 subdivisions, and you can set it to 16 subdivisions on the firmware.

**Comment by Voxel3DPrinting** [comment]
thanks!
