### ISSUE TITLE
MKS eagle not compatible with TFT?

### ISSUE THREAD

**Issue by Voxel3DPrinting** [makerbase-mks/MKS-EAGLE#7]
Dear,

I want to use my TFT 28 on my MKS eagle mainboard, I used to compile the firmware with serial port 1 0 and baudrate 250000, which worked.
However, now I cannot compile the marlin firmware, if the serial port is 0...

How can I use this screen??

**Comment by MKS-hosiey** [comment]
Configure the second serial port to 3.

**Comment by Voxel3DPrinting** [comment]
Thanks, this worked!
